language: node_js
node_js:
  - 10.16.0
branches:
  only:
  - production
cache:
  yarn: true
  npm: true

before_install:

install:
  - npm

deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production