language: node_js
node_js:
- 10.16.0
branches:
  only:
  - production
cache:
  yarn: true
  npm: true
before_install:
- openssl aes-256-cbc -K $encrypted_5ed7293ec541_key -iv $encrypted_5ed7293ec541_iv
  -in secret.json.enc -out secret.json -d
install:
- npm
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production
