language: node_js
node_js:
  - 10.16.0
branches:
  only:
    - production
cache:
  yarn: true
  directories: $HOME/google-cloud-sdk
before_install:

install:
  - yarn
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  'on': production
