name: Publish
on:
  push:
    branch:
      - nothing-yet

jobs:
  publish:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Install and Build
          env:
              GOOGLE_APPLICATION_CREDENTIALS: $
          run: |
            npm install
            npm run build
            npm run publish
